import type { Metadata } from "next";
import resume from "./resume.json";
import PrintButton from "./PrintButton";

// resume.json is generated by scripts/sync_resume.py from the job-agent bullet bank.
// Edit the bank, not this page or the JSON, to change the resume content.

export const metadata: Metadata = {
  title: "Resume | Daniel Rosenthal",
};

type Entry = (typeof resume.experience)[number];

const formatUpdated = (iso: string) =>
  new Date(`${iso}T12:00:00`).toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" });

function EntryCard({ entry }: { entry: Entry }) {
  return (
    <div className="glass hover-glass rounded-xl p-6 md:p-8">
      <div className="flex flex-col md:flex-row md:items-baseline md:justify-between gap-1">
        <h3 className="text-xl font-bold text-white">
          {entry.org}
          <span className="font-normal text-[var(--tertiary-color)]"> · {entry.title}</span>
        </h3>
        <p className="text-sm text-white/60 whitespace-nowrap">{entry.dates}</p>
      </div>
      <p className="text-xs uppercase tracking-wide text-white/50 mt-1">{entry.location}</p>
      <ul className="mt-4 space-y-3 list-disc pl-5 text-white/85 leading-relaxed marker:text-[var(--tertiary-color)]">
        {entry.bullets.map((bullet) => (
          <li key={bullet}>{bullet}</li>
        ))}
      </ul>
    </div>
  );
}

function SectionHeading({ children }: { children: React.ReactNode }) {
  return (
    <h2 className="text-sm uppercase tracking-wide text-[var(--tertiary-color)]/80 mb-4 mt-14">{children}</h2>
  );
}

export default function Resume() {
  const { header, skills, experience, projects, education, updated } = resume;
  const links = [
    { href: `mailto:${header.email}`, label: "email" },
    { href: header.linkedin, label: "linkedin" },
    { href: header.github, label: "github" },
  ];

  return (
    <div className="page-bg min-h-screen text-white resume-page">
      <main className="max-w-4xl mx-auto px-6 pt-40 pb-32">
        <section className="flex flex-col items-center md:items-start text-center md:text-left">
          <p className="text-sm uppercase tracking-wide text-[var(--tertiary-color)]/80 mb-2">resume</p>
          <h1 className="text-4xl md:text-5xl font-extrabold leading-tight">
            {header.name.toLowerCase()}<span className="text-[var(--tertiary-color)]">.</span>
            <span className="block text-lg font-normal mt-3 text-[var(--tertiary-color)]">
              software engineer · {header.address}
            </span>
          </h1>
          <div className="mt-6 flex flex-wrap justify-center md:justify-start items-center gap-4 text-white/80">
            {links.map((l) => (
              <a
                key={l.label}
                href={l.href}
                target="_blank"
                rel="noreferrer"
                className="hover:text-[var(--tertiary-color)] transition"
              >
                {l.label}
              </a>
            ))}
            <PrintButton />
          </div>
          {updated && <p className="mt-4 text-xs text-white/40">last updated {formatUpdated(updated)}</p>}
        </section>

        <SectionHeading>experience</SectionHeading>
        <div className="space-y-6">
          {experience.map((entry) => (
            <EntryCard key={entry.id} entry={entry} />
          ))}
        </div>

        <SectionHeading>projects</SectionHeading>
        <div className="space-y-6">
          {projects.map((entry) => (
            <EntryCard key={entry.id} entry={entry} />
          ))}
        </div>

        <SectionHeading>skills</SectionHeading>
        <div className="glass hover-glass rounded-xl p-6 md:p-8 space-y-5">
          {skills.map(({ group, items }) => (
            <div key={group}>
              <h3 className="text-sm font-semibold text-white/70 mb-2">{group}</h3>
              <div className="flex flex-wrap gap-2">
                {items.map((skill) => (
                  <span key={skill} className="glass-button rounded-md px-3 py-1 text-sm text-white">
                    {skill}
                  </span>
                ))}
              </div>
            </div>
          ))}
        </div>

        <SectionHeading>education</SectionHeading>
        <div className="space-y-6">
          {education.map((school) => (
            <div key={school.school} className="glass hover-glass rounded-xl p-6 md:p-8">
              <div className="flex flex-col md:flex-row md:items-baseline md:justify-between gap-1">
                <h3 className="text-xl font-bold text-white">{school.school}</h3>
                <p className="text-sm text-white/60">{school.dates}</p>
              </div>
              <ul className="mt-3 space-y-1 text-white/85">
                {school.lines.map((line) => (
                  <li key={line.text}>{line.text}</li>
                ))}
              </ul>
            </div>
          ))}
        </div>
      </main>
    </div>
  );
}
